use super::super::Applicability;
use census_domain::UsJurisdiction;

pub(crate) const TABLE: [Applicability; 29] = [
    Applicability {
        slug: "aia",
        jurisdictions: &[UsJurisdiction::Arizona],
        evidence: super::prose::AIA_EVIDENCE,
        refusal: super::prose::AIA_REFUSAL,
    },
    Applicability {
        slug: "athleticlive",
        jurisdictions: &[
            UsJurisdiction::Alabama,
            UsJurisdiction::Iowa,
            UsJurisdiction::Illinois,
            UsJurisdiction::Indiana,
            UsJurisdiction::Kansas,
            UsJurisdiction::Michigan,
            UsJurisdiction::Minnesota,
            UsJurisdiction::Missouri,
            UsJurisdiction::NorthDakota,
            UsJurisdiction::Nebraska,
            UsJurisdiction::Ohio,
            UsJurisdiction::Wisconsin,
        ],
        evidence: super::prose::ATHLETICLIVE_EVIDENCE,
        refusal: super::prose::ATHLETICLIVE_REFUSAL,
    },
    Applicability {
        slug: "athleticlive_athletes",
        jurisdictions: &[
            UsJurisdiction::Alabama,
            UsJurisdiction::Iowa,
            UsJurisdiction::Illinois,
            UsJurisdiction::Indiana,
            UsJurisdiction::Kansas,
            UsJurisdiction::Michigan,
            UsJurisdiction::Minnesota,
            UsJurisdiction::Missouri,
            UsJurisdiction::NorthDakota,
            UsJurisdiction::Nebraska,
            UsJurisdiction::Ohio,
            UsJurisdiction::Wisconsin,
        ],
        evidence: super::prose::ATHLETICLIVE_ATHLETES_EVIDENCE,
        refusal: super::prose::ATHLETICLIVE_ATHLETES_REFUSAL,
    },
    Applicability {
        slug: "athleticnet",
        jurisdictions: &UsJurisdiction::CENSUS_SCOPE,
        evidence: super::prose::ATHLETICNET_EVIDENCE,
        refusal: super::prose::ATHLETICNET_REFUSAL,
    },
    Applicability {
        slug: "ciac",
        jurisdictions: &[UsJurisdiction::Connecticut],
        evidence: super::prose::CIAC_EVIDENCE,
        refusal: super::prose::CIAC_REFUSAL,
    },
    Applicability {
        slug: "chsaa",
        jurisdictions: &[UsJurisdiction::Colorado],
        evidence: super::prose::CHSAA_EVIDENCE,
        refusal: super::prose::CHSAA_REFUSAL,
    },
    Applicability {
        slug: "coach_directories",
        jurisdictions: &[
            UsJurisdiction::NorthCarolina,
            UsJurisdiction::Alabama,
            UsJurisdiction::Arkansas,
            UsJurisdiction::Georgia,
            UsJurisdiction::Montana,
            UsJurisdiction::Mississippi,
            UsJurisdiction::SouthCarolina,
            UsJurisdiction::Idaho,
            UsJurisdiction::NewMexico,
            UsJurisdiction::Maryland,
            UsJurisdiction::DistrictOfColumbia,
            UsJurisdiction::Delaware,
            UsJurisdiction::Tennessee,
            UsJurisdiction::Wyoming,
            UsJurisdiction::NorthDakota,
        ],
        evidence: super::prose::COACH_DIRECTORIES_EVIDENCE,
        refusal: super::prose::COACH_DIRECTORIES_REFUSAL,
    },
    Applicability {
        slug: "coach_contacts",
        jurisdictions: &[
            UsJurisdiction::Arizona,
            UsJurisdiction::California,
            UsJurisdiction::Colorado,
            UsJurisdiction::DistrictOfColumbia,
            UsJurisdiction::Florida,
            UsJurisdiction::Georgia,
            UsJurisdiction::Iowa,
            UsJurisdiction::Illinois,
            UsJurisdiction::Indiana,
            UsJurisdiction::Kansas,
            UsJurisdiction::Michigan,
            UsJurisdiction::Minnesota,
            UsJurisdiction::Missouri,
            UsJurisdiction::NorthDakota,
            UsJurisdiction::Nebraska,
            UsJurisdiction::NewJersey,
            UsJurisdiction::Ohio,
            UsJurisdiction::Oregon,
            UsJurisdiction::Tennessee,
            UsJurisdiction::Texas,
            UsJurisdiction::Utah,
            UsJurisdiction::Wisconsin,
        ],
        evidence: super::prose::COACH_CONTACTS_EVIDENCE,
        refusal: super::prose::COACH_CONTACTS_REFUSAL,
    },
    Applicability {
        slug: "home_campus",
        jurisdictions: &[
            UsJurisdiction::California,
            UsJurisdiction::Florida,
            UsJurisdiction::NewJersey,
        ],
        evidence: super::prose::HOME_CAMPUS_EVIDENCE,
        refusal: super::prose::HOME_CAMPUS_REFUSAL,
    },
    Applicability {
        slug: "sidearm_staff",
        jurisdictions: &[UsJurisdiction::California],
        evidence: super::prose::SIDEARM_STAFF_EVIDENCE,
        refusal: super::prose::SIDEARM_STAFF_REFUSAL,
    },
    Applicability {
        slug: "bound",
        jurisdictions: &[UsJurisdiction::Iowa, UsJurisdiction::SouthDakota],
        evidence: super::prose::BOUND_EVIDENCE,
        refusal: super::prose::BOUND_REFUSAL,
    },
    Applicability {
        slug: "ihsa",
        jurisdictions: &[UsJurisdiction::Illinois],
        evidence: super::prose::IHSAA_EVIDENCE,
        refusal: super::prose::IHSAA_REFUSAL,
    },
    Applicability {
        slug: "ks",
        jurisdictions: &[UsJurisdiction::Kansas],
        evidence: super::prose::KSAA_EVIDENCE,
        refusal: super::prose::KSAA_REFUSAL,
    },
    Applicability {
        slug: "milesplit",
        jurisdictions: &UsJurisdiction::CENSUS_SCOPE,
        evidence: super::prose::MILESPPLIT_EVIDENCE,
        refusal: super::prose::MILESPPLIT_REFUSAL,
    },
    Applicability {
        slug: "mpa",
        jurisdictions: &[UsJurisdiction::Maine],
        evidence: super::prose::MPA_EVIDENCE,
        refusal: super::prose::MPA_REFUSAL,
    },
    Applicability {
        slug: "mshsl",
        jurisdictions: &[UsJurisdiction::Minnesota],
        evidence: super::prose::MSHSL_EVIDENCE,
        refusal: super::prose::MSHSL_REFUSAL,
    },
    Applicability {
        slug: "ohsaa",
        jurisdictions: &[UsJurisdiction::Ohio],
        evidence: super::prose::OHSA_EVIDENCE,
        refusal: super::prose::OHSA_REFUSAL,
    },
    Applicability {
        slug: "plain_names",
        jurisdictions: &[UsJurisdiction::NorthDakota, UsJurisdiction::Nebraska],
        evidence: super::prose::PLAIN_NAMES_EVIDENCE,
        refusal: super::prose::PLAIN_NAMES_REFUSAL,
    },
    Applicability {
        slug: "pa_piaa",
        jurisdictions: &[UsJurisdiction::Pennsylvania],
        evidence: super::prose::PA_PIAA_EVIDENCE,
        refusal: super::prose::PA_PIAA_REFUSAL,
    },
    Applicability {
        slug: "riil",
        jurisdictions: &[UsJurisdiction::RhodeIsland],
        evidence: super::prose::RIIL_EVIDENCE,
        refusal: super::prose::RIIL_REFUSAL,
    },
    Applicability {
        slug: "tfrrs",
        jurisdictions: &[
            UsJurisdiction::Florida,
            UsJurisdiction::Indiana,
            UsJurisdiction::NewHampshire,
        ],
        evidence: super::prose::TFRS_EVIDENCE,
        refusal: super::prose::TFRS_REFUSAL,
    },
    Applicability {
        slug: "wayzata",
        jurisdictions: &[
            UsJurisdiction::Iowa,
            UsJurisdiction::Minnesota,
            UsJurisdiction::Wisconsin,
        ],
        evidence: super::prose::WAYZATA_EVIDENCE,
        refusal: super::prose::WAYZATA_REFUSAL,
    },
    Applicability {
        slug: "wiaa",
        jurisdictions: &[UsJurisdiction::Wisconsin],
        evidence: super::prose::WIAA_EVIDENCE,
        refusal: super::prose::WIAA_REFUSAL,
    },
    Applicability {
        slug: "wiaa_results",
        jurisdictions: &[UsJurisdiction::Wisconsin],
        evidence: super::prose::WIAA_RESULTS_EVIDENCE,
        refusal: super::prose::WIAA_RESULTS_REFUSAL,
    },
    Applicability {
        slug: "nces",
        jurisdictions: &UsJurisdiction::CENSUS_SCOPE,
        evidence: super::prose::NCES_EVIDENCE,
        refusal: super::prose::NCES_REFUSAL,
    },
    Applicability {
        slug: "state_ed",
        jurisdictions: &[UsJurisdiction::NewYork],
        evidence: super::prose::STATE_ED_EVIDENCE,
        refusal: super::prose::STATE_ED_REFUSAL,
    },
    Applicability {
        slug: "tssaa",
        jurisdictions: &[UsJurisdiction::Tennessee],
        evidence: super::prose::TSSAA_EVIDENCE,
        refusal: super::prose::TSSAA_REFUSAL,
    },
    Applicability {
        slug: "uhsaa",
        jurisdictions: &[UsJurisdiction::Utah],
        evidence: super::prose::UHSAA_EVIDENCE,
        refusal: super::prose::UHSAA_REFUSAL,
    },
    super::ARBITER,
];
