//! The `UsJurisdiction` enum and the scope-related constants.
//!
//! The impl block lives in [`super::codes`]; Rust does not allow split inherent impls.

/// One of the fifty US states or the District of Columbia.
///
/// Variants are declared in the order [`UsJurisdiction::ALL`] lists them (alphabetical by name,
/// with the District of Columbia last), so `Ord` orders jurisdictions the way a report reads.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum UsJurisdiction {
    Alabama,
    Alaska,
    Arizona,
    Arkansas,
    California,
    Colorado,
    Connecticut,
    Delaware,
    Florida,
    Georgia,
    Hawaii,
    Idaho,
    Illinois,
    Indiana,
    Iowa,
    Kansas,
    Kentucky,
    Louisiana,
    Maine,
    Maryland,
    Massachusetts,
    Michigan,
    Minnesota,
    Mississippi,
    Missouri,
    Montana,
    Nebraska,
    Nevada,
    NewHampshire,
    NewJersey,
    NewMexico,
    NewYork,
    NorthCarolina,
    NorthDakota,
    Ohio,
    Oklahoma,
    Oregon,
    Pennsylvania,
    RhodeIsland,
    SouthCarolina,
    SouthDakota,
    Tennessee,
    Texas,
    Utah,
    Vermont,
    Virginia,
    Washington,
    WestVirginia,
    Wisconsin,
    Wyoming,
    DistrictOfColumbia,
}

impl UsJurisdiction {
    /// Every jurisdiction the census covers, in declaration order.
    pub const ALL: [Self; 51] = [
        Self::Alabama,
        Self::Alaska,
        Self::Arizona,
        Self::Arkansas,
        Self::California,
        Self::Colorado,
        Self::Connecticut,
        Self::Delaware,
        Self::Florida,
        Self::Georgia,
        Self::Hawaii,
        Self::Idaho,
        Self::Illinois,
        Self::Indiana,
        Self::Iowa,
        Self::Kansas,
        Self::Kentucky,
        Self::Louisiana,
        Self::Maine,
        Self::Maryland,
        Self::Massachusetts,
        Self::Michigan,
        Self::Minnesota,
        Self::Mississippi,
        Self::Missouri,
        Self::Montana,
        Self::Nebraska,
        Self::Nevada,
        Self::NewHampshire,
        Self::NewJersey,
        Self::NewMexico,
        Self::NewYork,
        Self::NorthCarolina,
        Self::NorthDakota,
        Self::Ohio,
        Self::Oklahoma,
        Self::Oregon,
        Self::Pennsylvania,
        Self::RhodeIsland,
        Self::SouthCarolina,
        Self::SouthDakota,
        Self::Tennessee,
        Self::Texas,
        Self::Utah,
        Self::Vermont,
        Self::Virginia,
        Self::Washington,
        Self::WestVirginia,
        Self::Wisconsin,
        Self::Wyoming,
        Self::DistrictOfColumbia,
    ];

    /// The jurisdictions a census **run** covers: the 48 continental states plus the District of
    /// Columbia (ADR-009).
    ///
    /// [`Self::ALL`] is what the domain *models*; this is what a run may touch. Alaska and Hawaii
    /// are declared above, are never acquired, and never appear in a coverage denominator — a run
    /// set that admits them has to be written as an explicit edit here, which is the point.
    pub const CENSUS_SCOPE: [Self; 49] = [
        Self::Alabama,
        Self::Arizona,
        Self::Arkansas,
        Self::California,
        Self::Colorado,
        Self::Connecticut,
        Self::Delaware,
        Self::Florida,
        Self::Georgia,
        Self::Idaho,
        Self::Illinois,
        Self::Indiana,
        Self::Iowa,
        Self::Kansas,
        Self::Kentucky,
        Self::Louisiana,
        Self::Maine,
        Self::Maryland,
        Self::Massachusetts,
        Self::Michigan,
        Self::Minnesota,
        Self::Mississippi,
        Self::Missouri,
        Self::Montana,
        Self::Nebraska,
        Self::Nevada,
        Self::NewHampshire,
        Self::NewJersey,
        Self::NewMexico,
        Self::NewYork,
        Self::NorthCarolina,
        Self::NorthDakota,
        Self::Ohio,
        Self::Oklahoma,
        Self::Oregon,
        Self::Pennsylvania,
        Self::RhodeIsland,
        Self::SouthCarolina,
        Self::SouthDakota,
        Self::Tennessee,
        Self::Texas,
        Self::Utah,
        Self::Vermont,
        Self::Virginia,
        Self::Washington,
        Self::WestVirginia,
        Self::Wisconsin,
        Self::Wyoming,
        Self::DistrictOfColumbia,
    ];

    /// The modelled jurisdictions a census run never covers, named so reports, tests and the
    /// workflow's admission check can all assert the same rule.
    pub const EXCLUDED_FROM_CENSUS: [Self; 2] = [Self::Alaska, Self::Hawaii];
}
