pub(crate) const TITLE: &str = "Athletes";

pub(crate) const HEADERS: [&str; 60] = [
    "Athlete ID",
    "Name",
    "Gender",
    "Graduation Year",
    "Observed Grade",
    "Observed School Year",
    "State",
    "School",
    "School ID",
    "School City",
    "TF",
    "XC",
    "Indoor",
    "Outdoor",
    "Event list",
    "Headline PR summary",
    "100m (s)",
    "200m (s)",
    "400m (s)",
    "800m (s)",
    "1600m (s)",
    "3200m (s)",
    "1 Mile (s)",
    "5000m (s)",
    "100m Hurdles (s)",
    "110m Hurdles (s)",
    "300m Hurdles (s)",
    "High Jump (m)",
    "Long Jump (m)",
    "Triple Jump (m)",
    "Pole Vault (m)",
    "Shot Put (m)",
    "Discus (m)",
    "Javelin (m)",
    "XC (s)",
    "Performance count",
    "Meet count",
    "Head TF Coach",
    "Head TF Coach Email",
    "Head XC Coach",
    "Head XC Coach Email",
    "Coach Professional Email",
    "Athletic Director",
    "AD Email",
    "School Athletics URL",
    "Public Recruiting GPA",
    "GPA Source",
    "All Emails (school)",
    "Preferred Recruiting Contact",
    "Preferred Contact Role",
    "Preferred Contact Email",
    "Contact Coverage State",
    "Athletic.net URL",
    "MileSplit URL",
    "Other profile URLs",
    "Sources Count",
    "Identity Status",
    "Coverage State",
    "Conflict Flag",
    "Review Status",
];

pub(crate) const WIDTHS: [u16; 60] = [
    20, 26, 10, 16, 12, 14, 8, 30, 16, 20, 8, 8, 8, 8, 30, 30, 12, 12, 12, 12, 12, 12, 12, 18, 18,
    18, 16, 16, 16, 16, 16, 16, 16, 12, 16, 12, 24, 32, 24, 32, 24, 32, 24, 24, 24, 24, 48, 30, 24,
    32, 28, 36, 36, 40, 14, 18, 18, 14, 14, 14,
];

pub(crate) const PR_EVENTS: [&str; 19] = [
    "Track100m",
    "Track200m",
    "Track400m",
    "Track800m",
    "Track1600m",
    "Track3200m",
    "Track1Mile",
    "Track5000m",
    "Track100mHurdles",
    "Track110mHurdles",
    "Track300mHurdles",
    "HighJump",
    "LongJump",
    "TripleJump",
    "PoleVault",
    "ShotPut",
    "Discus",
    "Javelin",
    "CrossCountry",
];
